### PR TITLE
Removed dead code

### PR DESCRIPTION
**Pull request by jrkhan**
Addresses dead code found in TopShotMarketV3

Addresses the following issue:
https://github.com/dapperlabs/nba-smart-contracts/issues/165

### CODE REVIEW

**Review by joshuahannan — APPROVED** [review]

**Comment by turbolent** [comment]
Thank you! 

Have you verified that this change is also valid on the current networks?

Also, maybe reference the issue, #165

**Comment by jrkhan** [comment]
> Have you verified that this change is also valid on the current networks?
Just checked this locally, and needed to adjust things a bit to both avoid dead code and get around the current compiler wanting to make sure unreachable code was returning a value. Should be resolved now.

**Comment by turbolent** [comment]
@jrkhan Sounds good, let me check this against the new Cadence version we're intending to deploy

**Comment by turbolent** [comment]
Confirmed that the changes will also work with the new version 👍

**Review by turbolent — APPROVED** [review]
Nice! Thank you

**Comment by j1010001** [comment]
Just want to make this clear - this needs to be deployed to MN before the next (mainnet 20) spork.

**Comment by turbolent** [comment]
@jrkhan Any update here?

**Comment by jrkhan** [comment]
> @jrkhan Any update here?

Deployed to testnet today -> planning to deploy to mainnet tomorrow mid day.

**Pull request merged**
